import/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('su-admin/', admin.site.urls),
    path('', include('reviewer.urls')),
    path('u/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

reviewer/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name="index"),

    # Legal URLs
    path('terms/', views.terms, name="terms"),
    path('privacy-policy/', views.privacy, name="privacy_policy"),
    path('disclaimer/', views.disclaimer, name="disclaimer"),

    # Course URLs
    path('course/', views.courselist, name="courselist"),
    path('course/<str:csubj>/<int:cnum>/', views.course, name="course"),
    re_path(r'^course/(?P<csubj>[a-zA-Z]+)/(?P<cnum>\d+)(?:/(?P<catchar>[c,l,r])(?:/(?P<cpage>\d+))?)?/$', views.coursecpage, name="coursecpage"),
    path('course/<str:csubj>/<int:cnum>/like/', views.comment_like, name="comment_like"),
    path('course/<str:csubj>/<int:cnum>/ref-get/', views.course_ref, name="course_ref"),

    # Super User URLs
    path('su/', views.admin , name="admin"),
    path('su/dashboard/', views.admin_dashboard , name="admin_dashboard"),
    path('su/users/', views.admin_users , name="admin_users"),

    path('su/course/', views.admin_course_list , name="admin_course_list"),
    path('su/course/<str:purpose>/get/', views.admin_get_course, name="admin_get_course"),
    path('su/course/<str:course_subj>/<str:course_num>/<str:purpose>/', views.admin_course_id, name="admin_course_id"),
    path('su/course/add/', views.admin_course, name="admin_course"),

    path('su/language/', views.admin_langlist , name="admin_langlist"),
    path('su/language/add/', views.admin_lang_add , name="admin_lang_add"),
    path('su/language/<str:id>/<str:purpose>/', views.admin_lang , name="admin_lang"),

    path('su/lessons/add/', views.admin_lessons_add , name="admin_lessons_add"),
    path('su/lessons/<str:id>/q/<str:qlang>/<str:purpose>/', views.admin_lessons_question_coding , name="admin_lesson_qcode"),
    path('su/lessons/<str:id>/q/<str:purpose>/', views.admin_lessons_question , name="admin_lesson_q"),
    path('su/lessons/<str:id>/<str:purpose>/', views.admin_lessons_crud , name="admin_lesson"),
    path('su/lessons/<str:id>/', views.admin_lessons_simple , name="admin_lesson_simple"),
    
    path('su/announcements/', views.admin_announcement , name="admin_announcement"),
    path('su/announcements/add/', views.admin_announcement_create , name="admin_announcement_create"),
    path('su/announcements/<str:id>/<str:purpose>/', views.admin_announcement_update , name="admin_announcement_update"),

    # User URLs
    path('u/register/', views.register, name="register"),
    path('u/settings/', views.user_settings, name="user_settings"),
    path('u/*/<str:username>/', views.user, name="user"),
    path('u/field_check/', views.user_redirect_info, name="user_redirect_info"),

    # Announcements
    path('announcements/', views.announcements, name="announcements"),
    path('announcements/<str:id>/', views.announcement_view, name="announcement_view"),

    # Test
    path('api/', views.google_test, name="google_test"),
    path('stream/', views.stream_test, name="stream_test"),

    # Robots.txt
    path('robots.txt', views.robots_txt ),
]

reviewer/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils import timezone

# Create your models here.

class Course(models.Model):
	name = models.CharField("Course Name", max_length=20, unique=True)
	code = models.CharField("Course Code", max_length=10)
	number = models.CharField("Course Number", max_length=10)
	number_len = models.PositiveSmallIntegerField(default=1)
	title = models.CharField("Course Title", max_length=50)
	description = models.TextField("Course Description", blank=True)
	old_curr = models.BooleanField("Pre-2018 Curriculum Exclusive?", default=False)
	visible = models.BooleanField("Visible?", default=True)
	prereqs = models.ManyToManyField('self', blank=True, default=None, symmetrical=False, related_name="preq")
	coreqs = models.ManyToManyField('self', blank=True, default=None,symmetrical=False , related_name="creq")
	lastupdated = models.DateTimeField("Last Updated", default=timezone.now)

	imageID = models.CharField("Photo ID", max_length=40, blank=True, null=True, default=None)

	def __str__(self):
		return	'{}'.format(self.name)

	def save(self, *args, **kwargs):
		self.number_len = len(self.number)
		return super(Course, self).save(*args, **kwargs)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['code', 'number'], name='unique codenums')
		]

class Language(models.Model):

	name = models.CharField(max_length=20, unique=True)
	imageID = models.CharField("Icon ID", max_length=40, blank=True, null=True, default=None)
	color = models.CharField(max_length=6, default="868686")

	def __str__(self):
		return	'{}'.format(self.name)

class ImportUser(AbstractUser):

	userID = models.AutoField(primary_key=True)
	username = models.CharField("Username", max_length=30, unique=True)
	first_name = models.CharField("First Name", max_length=30)
	middle_name = models.CharField("Middle Name", max_length=30, blank=True, null=True)
	last_name = models.CharField("Last Name", max_length=30)
	suffix = models.CharField("Suffix", max_length=10, blank=True, null=True)

	studentnum = models.PositiveIntegerField("Student Number", null=True)
	show_studentnum = models.BooleanField("Show Student Number", default=True)
	email = models.EmailField("E-mail", max_length=60)
	show_email = models.BooleanField("Show E-mail", default=True)
	course = models.CharField("Course/Degree Program", max_length=60)
	
	is_superuser = models.BooleanField("Is SuperUser?", default=False)
	exp = models.PositiveIntegerField("Experience Points", default=0)
	
	prof_picID = models.CharField("Prof Pic ID", max_length=40, blank=True, null=True, default=None)
	fave_lang = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Favorite Language")

	dark_mode = models.BooleanField("Dark Mode", default=False);
	notifications = models.BooleanField("Notifications", default=True);

	USERNAME_FIELD = 'username'

	def __str__(self):
		return	'{} - {}, {}'.format(self.username, self.last_name, self.first_name)


class Comment(models.Model):

	course_attr = models.ForeignKey(Course, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)
	body = models.CharField(max_length=240)
	
	imageID = models.CharField("Image ID", max_length=40, blank=True, null=True, default=None)
	date_posted = models.DateTimeField("Date Posted", default=timezone.now)

	def __str__(self):
		return	'Comment #{} - {}, {}'.format(self.id, self.course_attr, self.body[0:10])


class Likes(models.Model):

	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)

	def __str__(self):
		return	'Likes to Comment #{} - {}'.format(self.comment.id, self.user_attr)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['comment', 'user_attr'], name='unique like_combo')
		]

class Announcement(models.Model):

	title = models.CharField(max_length=30)
	body = JSONField()
	imageID = models.CharField("Image ID", max_length=40, blank=True, null=True, default=None)
	poster = models.ForeignKey(ImportUser, on_delete=models.SET_NULL, null=True)
	datepost = models.DateTimeField("Date Posted", default=timezone.now)

	def __str__(self):
		return	'{} - {}, {}'.format(self.title, self.datepost)

class Lesson(models.Model):

	name = models.CharField(max_length=50)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	rel_lesson = models.ManyToManyField('self', blank=True, default=None)
	lab_lesson = models.BooleanField("Lab Lesson?", default=False)
	extra = models.BooleanField("Extra?", default=False)
	verified = models.BooleanField("Verified?", default=False)
	verifier = models.CharField(max_length=50)

	order = models.PositiveIntegerField(default=1)

	def __str__(self):
		return	'{}: {}'.format(self.course, self.name)

class Question(models.Model):

	lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
	lang = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)

	module_content = models.TextField(null=True, blank=True, default=None)
	module_code = JSONField(null=True, default=None)
	custom_code = JSONField(null=True, default=None)
	qtype = models.CharField(max_length=10)

	def __str__(self):
		return	'{} - Question | Type: {}'.format(self.lesson.name, self.qtype)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['lesson', 'lang'], name='unique lesson-lang')
		]

class Partners():

	name = models.CharField(max_length=30, unique=True)
	imageID = models.CharField("Logo Image ID", max_length=40, blank=True, null=True, default=None)
	adImageID = models.CharField("Logo Image ID", max_length=40, blank=True, null=True, default=None)
	sponsor = models.BooleanField("Sponsor?", default=False)

	def __str__(self):
		return	'{}'.format(self.name)


class LessonStats(models.Model):
	
	lesson_attr = models.ForeignKey(Course, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)
	date_made = models.DateTimeField("Date", default=timezone.now)
	skips = models.PositiveSmallIntegerField(default=0)
	mistakes = models.PositiveSmallIntegerField(default=0)

	def __str__(self):
		return	'{0} on {1}| {2}'.format(self.user_attr, self.lesson_attr, self.date_made)


class BugReport(models.Model):

	name = models.CharField("Title", max_length=50)
	body = models.CharField("Body", max_length=300)
	status = models.PositiveSmallIntegerField("Status", default=0)
	lastupdated = models.DateTimeField("Last Updated", default=timezone.now)
	admin = models.ForeignKey(ImportUser, null=True, on_delete=models.SET_NULL, related_name="admin")
	user = models.ForeignKey(ImportUser, null=True, on_delete=models.SET_NULL, related_name="user")

	def __str__(self):
		return	'{} [{}]'.format(self.name, self.status)

class SiteSettings(models.Model):

	name = models.CharField(max_length=50, unique=True)
	body = models.CharField(max_length=300)

	def __str__(self):
		return	'{}'.format(self.name)

reviewer/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import ImportUser, Course


# Copy from models.py
class CourseForm(forms.Form):

	query = Course.objects.order_by('code', 'number_len', 'number')

	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'ex. CS 11', 'autocomplete': 'off'}))
	code = forms.CharField(max_length=10)
	number = forms.CharField(max_length=10)
	title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'ex. Computer Programming I', 'autocomplete': 'off'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder' : '', 'rows': 4}), required=False)
	old_curr = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False, initial=False)
	visible = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False, initial=True)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)
	lastupdated = timezone.now()
	imageID = forms.CharField(max_length=40)

	prereq = forms.ModelMultipleChoiceField(
		widget = forms.CheckboxSelectMultiple(),
        queryset = query,
        required = False
	)
	coreq = forms.ModelMultipleChoiceField(
		widget = forms.CheckboxSelectMultiple(),
        queryset = query,
        required = False
	)

class CommentForm(forms.Form):
	
	date_posted = timezone.now()

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop("request")
		user = self.request.user
		super(CommentForm, self).__init__(*args, **kwargs)

		disabled = True

		if user.is_anonymous:
			attributes = {
			'class': 'form-control -disabled', 
			'placeholder' : 'You must be logged in to comment.', 
			'readonly':'readonly'
			}
			
		else:
			attributes = { 
			'class': 'form-control comment-text-area', 
			'placeholder' : 'Comment', 
			'autocomplete': 'off'
			}
			disabled = False

		self.fields['body'] = forms.CharField(max_length=240, widget=forms.Textarea(attrs=attributes))
		self.fields['image'] = forms.ImageField(required=False, disabled=disabled)


class ImportUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm):
		model = ImportUser
		fields = ('username', 'first_name', 'middle_name', 'last_name', 'suffix', 'studentnum', 'show_studentnum', 'email', 'show_email', 'course', 'fave_lang')

class ImportUserChangeForm(UserChangeForm):

    class Meta:
        model = ImportUser
        fields = ('username', 'first_name', 'middle_name', 'last_name', 'suffix', 'studentnum', 'show_studentnum', 'email', 'show_email', 'course', 'fave_lang', 'dark_mode')

class LanguageForm(forms.Form):

	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}))
	imageID = forms.CharField(max_length=40)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)
	color = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'class': 'color-picker', 'autocomplete': 'off'}))

class ImportImageForm(forms.Form):

	imageID = forms.CharField(max_length=40)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)

reviewer/views/announcements.py
import json
from ..models import Announcement
from django.shortcuts import render


def announcement_view(request, id):

	announcement = Announcement.objects.get(id=id)

	context = {
		'announcement' : announcement,
		'announcement_json' : json.dumps(announcement.body),
	}

	return render(request, 'reviewer/announcement.html', context)


def announcements(request):

	announcements = Announcement.objects.order_by('-datepost')
	
	context = {'announcements': announcements}
	return render(request, 'reviewer/announcement-list.html', context)

reviewer/views/index.py
import json
from ..models import Announcement
from django.shortcuts import render

# Index View

def index(request):
	announcements = Announcement.objects.order_by('-datepost')[0:3]
	announcements_json = []

	for announcement in announcements:
		announcements_json.append(json.dumps(announcement.body))

	context = { 
		'announcements': announcements, 
		'announcements_json' : announcements_json,
		'is_home': True
	}

	return render(request, 'reviewer/index.html', context)

reviewer/views/misc.py
from ..models import BugReport
from django.conf import settings
from django.http import JsonResponse, StreamingHttpResponse
from django.shortcuts import render
import time

from ..custom import *

# Create your views here.

def terms(request):
	context = {}
	return render(request, 'reviewer/legal/terms.html', context)

def privacy(request):
	context = {}
	return render(request, 'reviewer/legal/privacy.html', context)

def disclaimer(request):
	context = {}
	return render(request, 'reviewer/legal/disclaimer.html', context)

def bug_report_list(request):
	mybugreports = BugReport.objects.filter(user=request.user).order_by('-lastupdated')
	context = {'my_bugreports': mybugreports}
	return render(request, 'reviewer/user/user-bug_report.html', context)

def google_test(request):
	service = gdrive_connect()
	trashed = gdrive_list_meta(service, query="trashed = true", pageSize=10)
	if trashed != None:
		for i in trashed:
			gdrive_delete_file(service, i)

	retjson = {'obj': gdrive_list_meta_children(service)}

	return JsonResponse(retjson)

def stream_chunks():
	i = 0
	while i < 30:
		yield '{}\n'.format(i)
		time.sleep(1)
		i = i+1

def stream_test(request):
	return StreamingHttpResponse(stream_chunks())

reviewer/views/robots.py
from django.http import HttpResponse
from django.views.decorators.http import require_GET

@require_GET
def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /su/",
        "Disallow: /u/settings/",
        "Disallow: /u/field_check/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

reviewer/templates/reviewer/courses/course-list.html
{% extends 'reviewer/base.html' %}


{% load static %}
{% block title %}
	Course List
{% endblock %}

{% block content %}
	<div class="container py-5 d-flex">
		<div class="w-100 py-5">
			<div class="d-flex justify-content-between">
				<h1 class="font-weight-bold">Course List</h1>

				{% if user.is_superuser %}
				<div class="d-inline-block">

					<a class="ajax-button" href="{% url 'admin_course' %}" data-toggle="modal" data-target="#importModal">
						<button type="button" class="btn btn-light px-3 d-flex" >
							<div class="my-auto d-flex">
								<i class="material-icons">
									library_add
								</i>
								<span class="my-auto ml-1 d-none d-md-block">
								Add Course</span>	
							</div>
						</button>
					</a>
				</div>
				{% endif %}
			</div>
			<div class="row">
				<div class="col-lg-8 course-list">
					<hr class="mb-3">
					{% if courselist.count == 0 %}
						<div class="text-center mt-4 d-flex">
							<div class="mx-auto d-flex text-muted"> 
								<i class="material-icons my-auto ml-0 mr-2">
									library_books
								</i>
								<span class="my-auto">No courses available to show</span>
							</div>
						</div>
					{% else %}
					
						{% for course in courselist %}
							<div class="py-3 mb-3 d-flex justify-content-between layer-container px-4" id="course-{{course.id}}">
								<div class="my-auto">
									<div class="d-inline-flex">
										<div class="my-auto mr-3 course-thumb" style="{% if course.imageID %}background-image: url('https://drive.google.com/thumbnail?id={{course.imageID | urlencode }}'); {%endif%}">
										</div>

										<div class="my-auto mx-auto">
											<h5>
												<span class="font-weight-bold">{{course.name}}</span> 
												{% if course.old_curr == True %}
													<i class="material-icons material-icon-sm text-danger info-help" title="This is part of an old curriculum.">error_outline</i>
												{% endif %}
											</h5>
											<h6>{{course.title}}</h6>
										</div> 	
									</div>
								</div>

								<a class="my-auto" href="{% url 'course' course.code|lower course.number %}">
									<button class="btn btn-primary btn-sm d-flex justify-content-center">
											<span class="my-auto d-none d-md-block">Start</span><i class="material-icons my-auto mx-1" style="font-size: 1em">arrow_forward</i>
									</button>
								</a>
							</div>
						{% endfor %}
					{% endif %}
				</div>
				<div class="col-lg-4 d-flex">
					<div class="mx-auto mr-lg-0">

						<div class="d-flex mb-3 ad-box">
							<span class="m-auto text-light h1 font-weight-bold">ADS</span>
						</div>
						<hr>
						<div class="d-none d-lg-block">
							<h4 class="d-inline-flex my-3">
								<i class="material-icons my-auto mr-2 import-font-primary">
									announcement
								</i>
								<span class="my-auto font-weight-bold">
									Announcements
								</span>
							</h4>
							{% if announcements.count == 0 %}
								<p>No announcements to show.</p>
							{% else %}
								{% for announcement in announcements %}
									<a href="{% url 'announcement_view' announcement.id %}">
										<div class="layer-container px-4 py-3 comment-username mb-2">
											<h6 class="font-weight-bold">{{announcement.title}}</h6>
											<small>{{announcement.datepost|date:"M d, Y, h:i A" }}</small>
										</div>
									</a>
								{% endfor %}
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script src="{% static 'reviewer/js/import_dragphoto.js' %}"></script>
	<script>
		{% if user.is_superuser %}
			$.get( "{% url 'admin_get_course' 'add' %}", function( data ) {
				$(".modal-body").html(data);
				$(".modal-title").html( $(".admin-title").html() );
				$(".admin-title").remove();
				importApp.dragPhoto.init();
			});
		{% endif %}
	</script>
	
{% endblock %}

reviewer/templates/reviewer/courses/course_add.html
<h2 class="admin-title mb-3 h2">
	<span class="d-inline-flex">
		<i class="material-icons my-auto mx-3 import-font-primary" style="font-size: inherit;">
			{% if title == 'Add Course'%}
					library_add
			{% elif title == 'Edit Course' %}
					edit
			{% endif %}
		</i>
		<span class="my-auto">
			<span class="font-weight-bold">{{title}}</span>
			{% if title == 'Edit Course' %}
				<p class="h6 text-muted">{{courseform.name.value}}</p>
			{% endif %}
		</span>
	</span>
</h2>

{% if error %}
	<div class="w-100 alert-danger p-3 d-flex">
		<i class="material-icons mr-3 my-auto ml-0">
		error_outline
		</i>
		<span class="my-auto">{{error}}</span>
	</div>
{% endif %}
<div class="d-flex flex-column p-3 pb-0">
	<form class="form-group mb-0" method="POST" action="
		{% if title == 'Add Course' %}
			{% url 'admin_course' %}
		{% else %}
			{% url 'admin_course_id' course_subj course_num 'edit' %}
		{% endif %}
		" enctype="multipart/form-data">
		{% csrf_token %}

		<div class="row">
			<div class="col-lg-6">
				<div class="form-control-group mb-3">
					<h6 class="font-weight-bold">Course Code & No.</h6>
					{{ courseform.name }}
				</div>

				<div class="form-control-group mb-3">
					<h6 class="font-weight-bold">Course Title</h6>
					{{ courseform.title }}
				</div>				
				
			</div>

			<div class="col-lg-6">
				<div class="form-control-group mb-3">
					<h6 class="font-weight-bold">Course Description</h6>
					{{ courseform.description }}
				</div>

			</div>

		</div>

		<div class="row w-100">
			<div class="col-lg-6 mr-4 col-3">
				<div class="form-control-group course-image-upload d-none position-absolute">
					<div>
						{{ courseform.imagehascleared }}
					</div>

					<div>
						<input type="file" name="image" accept="image/*" id="id_image">
						{% if courseform.imageID.value %}
							<a href="{{courseform.imageID.value}}">
							</a>
						{% endif %}
					</div>
				</div>
				<h6 class="font-weight-bold">Photo</h6>
				<button class="mx-auto border-dashed import-image-drag {% if user.is_authenticated %}import-image-drag-enabled{%else%}-disabled{%endif%}" data-file-target="course-image-upload" style="border-width: 1px" type="button" id="photo_upload" aria-describedby="addphoto-popper">
					{% if user.is_authenticated %}
						<div id="addphoto-popper" class="addphoto-popper p-3 position-absolute" role="tooltip">
							Add a photo
							<div id="arrow" data-popper-arrow></div>
						</div>
					{% endif %}
					<i class="material-icons p-4">
						add_a_photo
					</i>
				</button>
			</div>

			<div class="mt-4 d-flex w">
				<div class="form-group mr-4">
					<div class="d-inline-flex">
						<span class="my-auto mr-3 font-weight-bold">
						Old Course?
						</span> 
						<span class="my-auto d-none position-absolute old-curr-val">
							{{ courseform.old_curr }}
						</span>

						<i class="material-icons my-auto togglable {% if courseform.old_curr.value %}active-button{% endif %}" onclick="
							if ($('#id_old_curr').prop('checked')){
								$('#id_old_curr').removeAttr('checked');
							}
							else{
								$('#id_old_curr').attr('checked', 'checked');
							}
						">
							check_box{% if not courseform.old_curr.value %}_outline_blank{% endif %}
						</i>
					
						
					</div>
				</div>
 

				<div class="form-group">
					<p class="d-inline-flex">
						<span class="mr-3 my-auto font-weight-bold">Visibility</span> 
						<span class="d-none position-absolute my-auto course-vis-val">
							{{ courseform.visible }}
						</span>
						<i class="material-icons my-auto togglable {% if courseform.visible.value %}active-button{% endif %} " onclick="
							if ($('#id_visible').prop('checked')){
								$('#id_visible').removeAttr('checked');
							}
							else{
								$('#id_visible').attr('checked', 'checked');
							}
						">
							visibility{% if not courseform.visible.value %}_off{%endif%}
						</i>


					
					</p>
				</div>

			</div>
		</div>

		<div class="d-flex mt-3">
			<div class="mx-auto w-100">
				<h5>Prequisites and Corequisites</h5>

				<button class="btn btn-primary d-flex" type="button" onclick="$('table').fadeToggle()"><i class="material-icons material-icon-sm my-auto mr-2">library_books</i> <span class="my-auto">Toggle prerequisites/corequisites</span></button>

				<table class="table mt-3 req-table" style="display: none">
				  <thead>
				    <tr>
				      <th scope="col">Course Name</th>
				      <th scope="col" class="text-center">Prerequisite</th>
				      <th scope="col" class="text-center">Corequsite</th>
				    </tr>
				  </thead>
				  <tbody>

				  	<fieldset>
				  	{% if courses.count > 0 %}

						{% for course in courses %}
							<tr>
						      <td scope="row">
						      	{{course.name}}
						      	{% if not course.visible %}
							      	<i class="material-icons my-auto ml-2">
										visibility_off
									</i>
								{% endif %}
						      </td>
						      <td class="text-center">
						      	<input type="checkbox" class="form-check-input prereq" name="prereq" value="{{course.id}}" id="id_prereq_{{forloop.counter0}}">
						      </td>
						      <td class="text-center">
						      	<input type="checkbox" class="form-check-input coreq" name="coreq" value="{{course.id}}" id="id_coreq_{{forloop.counter0}}">
						      </td>
						    </tr>
						{% endfor %}
					{% else %}
						<tr>
							<td>
								<span class="text-muted text-center"> No other courses found. </span>
							</td>
						<tr>

					{% endif %}
					</fieldset>
				  </tbody>
				</table>	
			</div>


			<script>
				{% if course_prereq %} 
				var prereq_values = {{course_prereq}} ;

				for (i = 0; i < prereq_values.length ; i++){
					document.querySelector(".prereq[value='" + prereq_values[i] + "']").setAttribute('checked', 'checked');
				}

				{% endif %}
				
				{% if course_coreq %} 
					var coreq_values  = {{course_coreq}};
					for (i = 0; i < coreq_values.length ; i++){
						document.querySelector(".coreq[value='" + coreq_values[i] + "']").setAttribute('checked', 'checked');
					}
				{% endif%}		
			</script>
		</div>

		<hr>
		<div class="w-100 d-flex mt-3">
			<div class="mr-auto form-group w-50 my-auto">
				<h6 class="font-weight-bold d-inline-flex mr-2">
					<i class="material-icons my-auto material-icon-sm mr-1">
						verified_user
					</i>
					<span class="my-auto">
						Confirm Action
					</span>
				</h6>
				<input class="form-control my-3 w-100" name="password" type="password" placeholder="Type password to confirm" required>
			</div>
			<div class="form-group mt-auto">
				<input class="btn btn-primary ml-auto mr-auto mr-lg-0" type="submit" value="Submit">
			</div>	
		</div>	
			
	</form>
</div>