import/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('su-admin/', admin.site.urls),
    path('', include('reviewer.urls')),
    path('u/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

reviewer/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name="index"),

    # Legal URLs
    path('terms/', views.terms, name="terms"),
    path('privacy-policy/', views.privacy, name="privacy_policy"),
    path('disclaimer/', views.disclaimer, name="disclaimer"),

    # Course URLs
    path('course/', views.courselist, name="courselist"),
    path('course/<str:csubj>/<int:cnum>/', views.course, name="course"),
    re_path(r'^course/(?P<csubj>[a-zA-Z]+)/(?P<cnum>\d+)(?:/(?P<catchar>[c,l,r])(?:/(?P<cpage>\d+))?)?/$', views.coursecpage, name="coursecpage"),
    path('course/<str:csubj>/<int:cnum>/like/', views.comment_like, name="comment_like"),
    path('course/<str:csubj>/<int:cnum>/ref-get/', views.course_ref, name="course_ref"),

    # Super User URLs
    path('su/', views.admin , name="admin"),
    path('su/dashboard/', views.admin_dashboard , name="admin_dashboard"),
    path('su/users/', views.admin_users , name="admin_users"),

    path('su/course/', views.admin_course_list , name="admin_course_list"),
    path('su/course/<str:purpose>/get/', views.admin_get_course, name="admin_get_course"),
    path('su/course/<str:course_subj>/<str:course_num>/<str:purpose>/', views.admin_course_id, name="admin_course_id"),
    path('su/course/add/', views.admin_course, name="admin_course"),

    path('su/language/', views.admin_langlist , name="admin_langlist"),
    path('su/language/add/', views.admin_lang_add , name="admin_lang_add"),
    path('su/language/<str:id>/<str:purpose>/', views.admin_lang , name="admin_lang"),

    path('su/lessons/add/', views.admin_lessons_add , name="admin_lessons_add"),
    path('su/lessons/<str:id>/q/<str:qlang>/<str:purpose>/', views.admin_lessons_question_coding , name="admin_lesson_qcode"),
    path('su/lessons/<str:id>/q/<str:purpose>/', views.admin_lessons_question , name="admin_lesson_q"),
    path('su/lessons/<str:id>/<str:purpose>/', views.admin_lessons_crud , name="admin_lesson"),
    path('su/lessons/<str:id>/', views.admin_lessons_simple , name="admin_lesson_simple"),
    
    path('su/announcements/', views.admin_announcement , name="admin_announcement"),
    path('su/announcements/add/', views.admin_announcement_create , name="admin_announcement_create"),
    path('su/announcements/<str:id>/<str:purpose>/', views.admin_announcement_update , name="admin_announcement_update"),

    # User URLs
    path('u/register/', views.register, name="register"),
    path('u/settings/', views.user_settings, name="user_settings"),
    path('u/*/<str:username>/', views.user, name="user"),
    path('u/field_check/', views.user_redirect_info, name="user_redirect_info"),

    # Announcements
    path('announcements/', views.announcements, name="announcements"),
    path('announcements/<str:id>/', views.announcement_view, name="announcement_view"),

    # Test
    path('api/', views.google_test, name="google_test"),
    path('stream/', views.stream_test, name="stream_test"),

    # Robots.txt
    path('robots.txt', views.robots_txt ),
]

reviewer/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils import timezone

# Create your models here.

class Course(models.Model):
	name = models.CharField("Course Name", max_length=20, unique=True)
	code = models.CharField("Course Code", max_length=10)
	number = models.CharField("Course Number", max_length=10)
	number_len = models.PositiveSmallIntegerField(default=1)
	title = models.CharField("Course Title", max_length=50)
	description = models.TextField("Course Description", blank=True)
	old_curr = models.BooleanField("Pre-2018 Curriculum Exclusive?", default=False)
	visible = models.BooleanField("Visible?", default=True)
	prereqs = models.ManyToManyField('self', blank=True, default=None, symmetrical=False, related_name="preq")
	coreqs = models.ManyToManyField('self', blank=True, default=None,symmetrical=False , related_name="creq")
	lastupdated = models.DateTimeField("Last Updated", default=timezone.now)

	imageID = models.CharField("Photo ID", max_length=40, blank=True, null=True, default=None)

	def __str__(self):
		return	'{}'.format(self.name)

	def save(self, *args, **kwargs):
		self.number_len = len(self.number)
		return super(Course, self).save(*args, **kwargs)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['code', 'number'], name='unique codenums')
		]

class Language(models.Model):

	name = models.CharField(max_length=20, unique=True)
	imageID = models.CharField("Icon ID", max_length=40, blank=True, null=True, default=None)
	color = models.CharField(max_length=6, default="868686")

	def __str__(self):
		return	'{}'.format(self.name)

class ImportUser(AbstractUser):

	userID = models.AutoField(primary_key=True)
	username = models.CharField("Username", max_length=30, unique=True)
	first_name = models.CharField("First Name", max_length=30)
	middle_name = models.CharField("Middle Name", max_length=30, blank=True, null=True)
	last_name = models.CharField("Last Name", max_length=30)
	suffix = models.CharField("Suffix", max_length=10, blank=True, null=True)

	studentnum = models.PositiveIntegerField("Student Number", null=True)
	show_studentnum = models.BooleanField("Show Student Number", default=True)
	email = models.EmailField("E-mail", max_length=60)
	show_email = models.BooleanField("Show E-mail", default=True)
	course = models.CharField("Course/Degree Program", max_length=60)
	
	is_superuser = models.BooleanField("Is SuperUser?", default=False)
	exp = models.PositiveIntegerField("Experience Points", default=0)
	
	prof_picID = models.CharField("Prof Pic ID", max_length=40, blank=True, null=True, default=None)
	fave_lang = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Favorite Language")

	dark_mode = models.BooleanField("Dark Mode", default=False);
	notifications = models.BooleanField("Notifications", default=True);

	USERNAME_FIELD = 'username'

	def __str__(self):
		return	'{} - {}, {}'.format(self.username, self.last_name, self.first_name)


class Comment(models.Model):

	course_attr = models.ForeignKey(Course, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)
	body = models.CharField(max_length=240)
	
	imageID = models.CharField("Image ID", max_length=40, blank=True, null=True, default=None)
	date_posted = models.DateTimeField("Date Posted", default=timezone.now)

	def __str__(self):
		return	'Comment #{} - {}, {}'.format(self.id, self.course_attr, self.body[0:10])


class Likes(models.Model):

	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)

	def __str__(self):
		return	'Likes to Comment #{} - {}'.format(self.comment.id, self.user_attr)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['comment', 'user_attr'], name='unique like_combo')
		]

class Announcement(models.Model):

	title = models.CharField(max_length=30)
	body = JSONField()
	imageID = models.CharField("Image ID", max_length=40, blank=True, null=True, default=None)
	poster = models.ForeignKey(ImportUser, on_delete=models.SET_NULL, null=True)
	datepost = models.DateTimeField("Date Posted", default=timezone.now)

	def __str__(self):
		return	'{} - {}, {}'.format(self.title, self.datepost)

class Lesson(models.Model):

	name = models.CharField(max_length=50)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	rel_lesson = models.ManyToManyField('self', blank=True, default=None)
	lab_lesson = models.BooleanField("Lab Lesson?", default=False)
	extra = models.BooleanField("Extra?", default=False)
	verified = models.BooleanField("Verified?", default=False)
	verifier = models.CharField(max_length=50)

	order = models.PositiveIntegerField(default=1)

	def __str__(self):
		return	'{}: {}'.format(self.course, self.name)

class Question(models.Model):

	lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
	lang = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)

	module_content = models.TextField(null=True, blank=True, default=None)
	module_code = JSONField(null=True, default=None)
	custom_code = JSONField(null=True, default=None)
	qtype = models.CharField(max_length=10)

	def __str__(self):
		return	'{} - Question | Type: {}'.format(self.lesson.name, self.qtype)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['lesson', 'lang'], name='unique lesson-lang')
		]

class Partners():

	name = models.CharField(max_length=30, unique=True)
	imageID = models.CharField("Logo Image ID", max_length=40, blank=True, null=True, default=None)
	adImageID = models.CharField("Logo Image ID", max_length=40, blank=True, null=True, default=None)
	sponsor = models.BooleanField("Sponsor?", default=False)

	def __str__(self):
		return	'{}'.format(self.name)


class LessonStats(models.Model):
	
	lesson_attr = models.ForeignKey(Course, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)
	date_made = models.DateTimeField("Date", default=timezone.now)
	skips = models.PositiveSmallIntegerField(default=0)
	mistakes = models.PositiveSmallIntegerField(default=0)

	def __str__(self):
		return	'{0} on {1}| {2}'.format(self.user_attr, self.lesson_attr, self.date_made)


class BugReport(models.Model):

	name = models.CharField("Title", max_length=50)
	body = models.CharField("Body", max_length=300)
	status = models.PositiveSmallIntegerField("Status", default=0)
	lastupdated = models.DateTimeField("Last Updated", default=timezone.now)
	admin = models.ForeignKey(ImportUser, null=True, on_delete=models.SET_NULL, related_name="admin")
	user = models.ForeignKey(ImportUser, null=True, on_delete=models.SET_NULL, related_name="user")

	def __str__(self):
		return	'{} [{}]'.format(self.name, self.status)

class SiteSettings(models.Model):

	name = models.CharField(max_length=50, unique=True)
	body = models.CharField(max_length=300)

	def __str__(self):
		return	'{}'.format(self.name)

reviewer/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import ImportUser, Course


# Copy from models.py
class CourseForm(forms.Form):

	query = Course.objects.order_by('code', 'number_len', 'number')

	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'ex. CS 11', 'autocomplete': 'off'}))
	code = forms.CharField(max_length=10)
	number = forms.CharField(max_length=10)
	title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'ex. Computer Programming I', 'autocomplete': 'off'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder' : '', 'rows': 4}), required=False)
	old_curr = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False, initial=False)
	visible = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False, initial=True)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)
	lastupdated = timezone.now()
	imageID = forms.CharField(max_length=40)

	prereq = forms.ModelMultipleChoiceField(
		widget = forms.CheckboxSelectMultiple(),
        queryset = query,
        required = False
	)
	coreq = forms.ModelMultipleChoiceField(
		widget = forms.CheckboxSelectMultiple(),
        queryset = query,
        required = False
	)

class CommentForm(forms.Form):
	
	date_posted = timezone.now()

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop("request")
		user = self.request.user
		super(CommentForm, self).__init__(*args, **kwargs)

		disabled = True

		if user.is_anonymous:
			attributes = {
			'class': 'form-control -disabled', 
			'placeholder' : 'You must be logged in to comment.', 
			'readonly':'readonly'
			}
			
		else:
			attributes = { 
			'class': 'form-control comment-text-area', 
			'placeholder' : 'Comment', 
			'autocomplete': 'off'
			}
			disabled = False

		self.fields['body'] = forms.CharField(max_length=240, widget=forms.Textarea(attrs=attributes))
		self.fields['image'] = forms.ImageField(required=False, disabled=disabled)


class ImportUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm):
		model = ImportUser
		fields = ('username', 'first_name', 'middle_name', 'last_name', 'suffix', 'studentnum', 'show_studentnum', 'email', 'show_email', 'course', 'fave_lang')

class ImportUserChangeForm(UserChangeForm):

    class Meta:
        model = ImportUser
        fields = ('username', 'first_name', 'middle_name', 'last_name', 'suffix', 'studentnum', 'show_studentnum', 'email', 'show_email', 'course', 'fave_lang', 'dark_mode')

class LanguageForm(forms.Form):

	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}))
	imageID = forms.CharField(max_length=40)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)
	color = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'class': 'color-picker', 'autocomplete': 'off'}))

class ImportImageForm(forms.Form):

	imageID = forms.CharField(max_length=40)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)

reviewer/views/announcements.py
import json
from ..models import Announcement
from django.shortcuts import render


def announcement_view(request, id):

	announcement = Announcement.objects.get(id=id)

	context = {
		'announcement' : announcement,
		'announcement_json' : json.dumps(announcement.body),
	}

	return render(request, 'reviewer/announcement.html', context)


def announcements(request):

	announcements = Announcement.objects.order_by('-datepost')
	
	context = {'announcements': announcements}
	return render(request, 'reviewer/announcement-list.html', context)

reviewer/views/index.py
import json
from ..models import Announcement
from django.shortcuts import render

# Index View

def index(request):
	announcements = Announcement.objects.order_by('-datepost')[0:3]
	announcements_json = []

	for announcement in announcements:
		announcements_json.append(json.dumps(announcement.body))

	context = { 
		'announcements': announcements, 
		'announcements_json' : announcements_json,
		'is_home': True
	}

	return render(request, 'reviewer/index.html', context)

reviewer/views/misc.py
from ..models import BugReport
from django.conf import settings
from django.http import JsonResponse, StreamingHttpResponse
from django.shortcuts import render
import time

from ..custom import *

# Create your views here.

def terms(request):
	context = {}
	return render(request, 'reviewer/legal/terms.html', context)

def privacy(request):
	context = {}
	return render(request, 'reviewer/legal/privacy.html', context)

def disclaimer(request):
	context = {}
	return render(request, 'reviewer/legal/disclaimer.html', context)

def bug_report_list(request):
	mybugreports = BugReport.objects.filter(user=request.user).order_by('-lastupdated')
	context = {'my_bugreports': mybugreports}
	return render(request, 'reviewer/user/user-bug_report.html', context)

def google_test(request):
	service = gdrive_connect()
	trashed = gdrive_list_meta(service, query="trashed = true", pageSize=10)
	if trashed != None:
		for i in trashed:
			gdrive_delete_file(service, i)

	retjson = {'obj': gdrive_list_meta_children(service)}

	return JsonResponse(retjson)

def stream_chunks():
	i = 0
	while i < 30:
		yield '{}\n'.format(i)
		time.sleep(1)
		i = i+1

def stream_test(request):
	return StreamingHttpResponse(stream_chunks())

reviewer/views/robots.py
from django.http import HttpResponse
from django.views.decorators.http import require_GET

@require_GET
def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /su/",
        "Disallow: /u/settings/",
        "Disallow: /u/field_check/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

reviewer/templates/reviewer/admin/courses/lessons/lessons.html
{% extends 'reviewer/admin/admin.html' %}

{% load static %}
{% block title %}
	{{title}}
{% endblock %}

{% block admin_side %}
	<div class="tab-pane fade show active" id="v-pills-courses" role="tabpanel" aria-labelledby="v-pills-courses-tab">
		{% include 'reviewer/admin/courses/lessons/lessons_add.html' %}
	</div>
{% endblock %}

{% block scripts %}
	{% if title == 'Edit Lesson' %}
	<script src="{% static 'reviewer/js/import_lessons.js' %}"></script>
	<script>
		$('.modal-dialog').addClass('modal-dialog-centered')
		$.get( "{% url 'admin_lesson' edit_lesson.pk 'question' %}", function( data ) {
			$(".modal-body").html(data);
			$(".modal-title").html( $(".modal-body .admin-title").html() );
			$(".modal-body .admin-title").remove();
		});

		$('body').on('click', '.delete-question', function (e) {
			confirm('Are you sure you want to delete this question?')? null: e.preventDefault();
	    });

	    $('body').on('click', ".import-question-create", function (e) {
			e.preventDefault();
			if (!$(this).prop("disabled"))
				importApp.questions.create('lessons-q-form', "{% url 'admin_lesson' edit_lesson.id 'question' %}");
	    });

	    $(document).on('change', ".import-codelang .codelang-select", function(){

	    	var selection = $(this);
	    	let currentLangID = selection.find("option[selected]").val();
	    	var langChange = confirm(`Change the language setting to ${otherlang[selection.val()].lang}?`);

	    	if (langChange){
	    		selection.find("option[selected]").removeAttr("selected");
		    	selection.find(`option[value=${selection.val()}]`).attr("selected", "selected");
		    	selection.parent().find(".lang-badge").css("background-image", `url('https://drive.google.com/thumbnail?id=${otherlang[selection.val()].imageID}&sz=s100')`);
		    	
		    	let selectedVals = $(".import-codelang .codelang-select option[selected]").map(function(){ return $(this).val() }).get();

		    	let remOpts = [];
		    	for (const [key, value] of Object.entries(otherlang)) {
		    		selectedVals.includes(key)? null: remOpts.push(value);
				}

				remOpts = remOpts.sort(function (a, b) { return a.lang.localeCompare( b.lang ) });

				let langOptions = "";
				for (var opts of remOpts){
		    		langOptions += `<option value="${opts.id}">${opts.lang}</option>`;
				}

				$(".import-codelang .codelang-select option:not([selected])").remove();
		    	$(".import-codelang .codelang-select").append(langOptions);

		    	if (importApp.requests.ajax) {
					importApp.requests.ajax.abort();
				}

				let qlesson = selection.parents(".lesson-question");
				let classes = ['module', 'build', 'delete'];
				for (var cla of classes){
					qlesson.find(`.${cla}-question`).attr("href", '#');
				}

		 		importApp.requests.ajax = $.ajax({
					url: encodeURI("{% url 'admin_lesson_q' edit_lesson.id 'lang-change' %}"),
					method: "post",
					data: {'before': currentLangID, 'after': selection.val() },
					headers: {'X-CSRFToken': importApp.csrfToken },
					success: function (response, status, xhr){
						for (var cla of classes){
							qlesson.find(`.${cla}-question`).attr("href", response.qlang_template.replace("%5C%25url%5C%25", cla) );
						}
					}
				});
	    	}
	    	else{
	    		selection.val(currentLangID);
	    	}
	    	
		});

	</script>

	{% endif %}
{% endblock %}

reviewer/templates/reviewer/admin/courses/lessons/lessons_add.html
<div>
	<a href="{% url 'admin_course_id' edit_lesson.course.code edit_lesson.course.number 'lessons' %}" class="my-auto text-muted">
		<small class="d-inline-flex">
			<i class="material-icons material-icon-sm mr-1 my-auto">
				arrow_back
			</i>
			<span>Back to {{edit_lesson.course.name}}</span>
		</small>
	</a>
</div>
<hr>
<h2 class="admin-title my-3 h2 d-inline-block">
	<span class="d-inline-flex">
		<i class="material-icons my-auto mx-3 import-font-primary" style="font-size: inherit;">
			{% if title == 'Add Lesson'%}
				add
			{% elif title == 'Edit Lesson' %}
				edit
			{% endif %}
		</i>
		<span class="my-auto">
			<span class="font-weight-bold">{{title}}</span>
			{% if title == 'Edit Lesson' %}
				<p class="h6 text-muted d-flex">
					<span class="my-auto">{{edit_lesson.course.name}}</span>
					<i class="material-icons material-icon-sm mx-1 my-auto">
						arrow_forward
					</i>
					<span class="my-auto">{{edit_lesson.name}}</span>
				</p>
			{% endif %}
		</span>
	</span>
</h2>

{% if error %}
	<div class="w-100 alert-danger p-3 d-flex">
		<i class="material-icons mr-3 my-auto ml-0">
		error_outline
		</i>
		<span class="my-auto">{{error}}</span>
	</div>
{% endif %}
<div class="d-flex flex-column pl-3">

	<h4 class="font-weight-bold">Lesson Settings</h4>
	<form class="form-group my-3" id="lessons-form" method="POST" action="
	{% if title == 'Add Lesson'%}
		{% url 'admin_lessons_add' %}
	{% elif title == 'Edit Lesson' %}
		{% url 'admin_lesson' edit_lesson.id 'edit' %}
	{% endif %}
	" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="row">
			<div class="col-lg-6">
				<div class="form-group">
					<label>
						<strong>Name</strong>
						<span class="import-font-primary">*</span> 
					</label>
					<input class="form-control pr-5 mx-0" type="text" name="name" value="{{edit_lesson.name}}" autocomplete="off" required>
					<div class="invalid-feedback">
						This field is required.
					</div>
				
				</div>

				<div class="form-group">
					<label>
						<strong>Course</strong>
						<span class="import-font-primary">*</span> 
					</label>
					<select class="form-control" name="course" id="select_course">
						{% for course in courses %}
						  <option value="{{course.pk}}"
						  {% if course == select_course or course == edit.lesson.course or forloop.counter0 == 0 and not edit_lesson.course and not select_course %}selected{%endif%}>{{course.name}}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group">
					<label>
						<strong>Related Lessons</strong> 
					</label>
					<select class="form-control" name="related" id="select_related">
						<option value="" selected>None</option>
						{% if rel_lessons.count > 0 %}
							{% for less in rel_lessons %}
							  	<option value="{{less.pk}}">{{less.name}}</option>
							{% endfor %}
						{% endif %}
					</select>
				</div>
			</div>
			<div class="col-lg-6">
					<div class="d-flex flex-wrap flex-column align-items-start">
						<div class="form-group">
							<div class="d-flex mr-2">
								<label class="my-auto mr-auto ml-0 font-weight-bold">Extra Lesson?</label>

								<span class="my-auto d-none position-absolute extra-val">
									<input type="checkbox" name="lesson_extra" value="extra">
								</span>

								<i class="material-icons my-auto mr-2 ml-2 togglable {% if edit_lesson.extra %}active-button{% endif %}" onclick="$('.extra-val input').click();">
									check_box{% if not edit_lesson.extra %}_outline_blank{% endif %}
								</i>

								<span class="d-none d-md-block icaption my-auto {% if edit_lesson.extra %}active-button{% endif %}">
									{% if edit_lesson.extra %}On{% else %}Off{% endif %}
								</span>
							</div>
							<small class="text-muted">Extra Lessons are lessons that are not included in the curriculum but beneficial to understand other lessons.</small>
						</div>

						<div class="form-group">
							<div class="d-flex">
								<label class="my-auto mr-auto ml-0 font-weight-bold">Lab Lesson?</label>

								<span class="my-auto d-none position-absolute lab-val">
									<input type="checkbox" name="lesson_lab" value="lab">
								</span>

								<i class="material-icons my-auto mr-2 ml-2 togglable {% if edit_lesson.lab_lesson %}active-button{% endif %}" onclick="$('.lab-val input').click();">
									check_box{% if not edit_lesson.lab_lesson %}_outline_blank{% endif %}
								</i>

								<span class="d-none d-md-block icaption my-auto {% if edit_lesson.lab_lesson %}active-button{% endif %}">
									{% if edit_lesson.lab_lesson %}On{% else %}Off{% endif %}
								</span>
							</div>
							<small class="text-muted">Lab Lessons are lessons that are exclusive to the lab component of the course.</small>
						</div>

						<div class="form-group">
							<div class="d-flex my-auto">
								<label class="my-auto mr-auto ml-0 font-weight-bold">Verified Status</label>

								<span class="my-auto d-none position-absolute verified-val">
									<input type="checkbox" name="lesson_verified" value="verified">
								</span>

								<i class="material-icons my-auto mr-2 ml-2 togglable {% if edit_lesson.verified %}active-button{% endif %}" onclick="$('.verified-val input').click();">
									check_box{% if not edit_lesson.verified %}_outline_blank{% endif %}
								</i>

								<span class="d-none d-md-block icaption my-auto {% if edit_lesson.verified %}active-button{% endif %}">
									{% if edit_lesson.verified %}On{% else %}Off{% endif %}
								</span>
							</div>
							<small class="text-muted">Verified Lessons are lessons that are checked by a trusted source and is verified to be correct.</small>
						</div>
					</div>

					<div class="my-auto">
						<label>
							<strong>Verified By:</strong> 
						</label>
						<input class="form-control pr-5 mx-0" type="text" name="verifiedby" value="{{edit_lesson.verifier}}" autocomplete="off">
					</div>

			</div>
		</div>
	
	</form>

	<div>
		{% if title == "Add Lesson" %}
			<p> You can create questions for the lessons after submitting the form. </p>
		{% else %}
			<div class="d-flex justify-content-between mt-4">
				<h4 class="font-weight-bold my-auto">Questions</h4>

				<a href="#" data-toggle="modal" data-target="#importModal" class="my-auto">
					<button type="button" class="btn btn-light px-3 d-flex">
						<div class="my-auto d-flex">
							<i class="material-icons">
								add
							</i>
							<span class="my-auto ml-1 d-none d-md-block">
								Add Question
							</span>	
						</div>
					</button>
				</a>
			</div>

			<div class="questions d-flex mt-3 flex-column">
				{% if edit_lesson.question_set.count == 0 %}
					<div class="mx-auto d-flex text-muted"> 
						<i class="material-icons my-auto ml-0 mr-2">
							question_answer
						</i>
						<span class="my-auto">No questions available to show</span>
					</div>
				{% else %}
					<script>
						var otherlang = {
							{% for lelang in all_lang.all %}
								{% if forloop.counter0 != 0 %},{% endif %}
								{{lelang.id}} : { 	
									lang: "{{lelang.name}}", 
									id: {{lelang.id}},
									imageID: "{{lelang.imageID}}"
								}
							{% endfor %}
						};
					</script>
					{% for question in edit_lesson_qset.all %}
						{% include 'reviewer/admin/courses/lessons/questions/questions_partial.html' %}
					{% endfor %}
				{% endif %}
			</div>
		{% endif %}
	</div>
</div>

<hr>

<div class="float-right">
	<button class="btn btn-primary d-inline-flex" type="submit" form="lessons-form">
		<i class="material-icons my-auto material-icon-sm mr-lg-2">
			save
		</i>
		<span class="my-auto d-none d-lg-block">Save</span>
	</button>
</div>