import/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('su-admin/', admin.site.urls),
    path('', include('reviewer.urls')),
    path('u/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

reviewer/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name="index"),

    # Legal URLs
    path('terms/', views.terms, name="terms"),
    path('privacy-policy/', views.privacy, name="privacy_policy"),
    path('disclaimer/', views.disclaimer, name="disclaimer"),

    # Course URLs
    path('course/', views.courselist, name="courselist"),
    path('course/<str:csubj>/<int:cnum>/', views.course, name="course"),
    re_path(r'^course/(?P<csubj>[a-zA-Z]+)/(?P<cnum>\d+)(?:/(?P<catchar>[c,l,r])(?:/(?P<cpage>\d+))?)?/$', views.coursecpage, name="coursecpage"),
    path('course/<str:csubj>/<int:cnum>/like/', views.comment_like, name="comment_like"),
    path('course/<str:csubj>/<int:cnum>/ref-get/', views.course_ref, name="course_ref"),

    # Super User URLs
    path('su/', views.admin , name="admin"),
    path('su/dashboard/', views.admin_dashboard , name="admin_dashboard"),
    path('su/users/', views.admin_users , name="admin_users"),

    path('su/course/', views.admin_course_list , name="admin_course_list"),
    path('su/course/<str:purpose>/get/', views.admin_get_course, name="admin_get_course"),
    path('su/course/<str:course_subj>/<str:course_num>/<str:purpose>/', views.admin_course_id, name="admin_course_id"),
    path('su/course/add/', views.admin_course, name="admin_course"),

    path('su/language/', views.admin_langlist , name="admin_langlist"),
    path('su/language/add/', views.admin_lang_add , name="admin_lang_add"),
    path('su/language/<str:id>/<str:purpose>/', views.admin_lang , name="admin_lang"),

    path('su/lessons/add/', views.admin_lessons_add , name="admin_lessons_add"),
    path('su/lessons/<str:id>/q/<str:qlang>/<str:purpose>/', views.admin_lessons_question_coding , name="admin_lesson_qcode"),
    path('su/lessons/<str:id>/q/<str:purpose>/', views.admin_lessons_question , name="admin_lesson_q"),
    path('su/lessons/<str:id>/<str:purpose>/', views.admin_lessons_crud , name="admin_lesson"),
    path('su/lessons/<str:id>/', views.admin_lessons_simple , name="admin_lesson_simple"),
    
    path('su/announcements/', views.admin_announcement , name="admin_announcement"),
    path('su/announcements/add/', views.admin_announcement_create , name="admin_announcement_create"),
    path('su/announcements/<str:id>/<str:purpose>/', views.admin_announcement_update , name="admin_announcement_update"),

    # User URLs
    path('u/register/', views.register, name="register"),
    path('u/settings/', views.user_settings, name="user_settings"),
    path('u/*/<str:username>/', views.user, name="user"),
    path('u/field_check/', views.user_redirect_info, name="user_redirect_info"),

    # Announcements
    path('announcements/', views.announcements, name="announcements"),
    path('announcements/<str:id>/', views.announcement_view, name="announcement_view"),

    # Test
    path('api/', views.google_test, name="google_test"),
    path('stream/', views.stream_test, name="stream_test"),

    # Robots.txt
    path('robots.txt', views.robots_txt ),
]

reviewer/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils import timezone

# Create your models here.

class Course(models.Model):
	name = models.CharField("Course Name", max_length=20, unique=True)
	code = models.CharField("Course Code", max_length=10)
	number = models.CharField("Course Number", max_length=10)
	number_len = models.PositiveSmallIntegerField(default=1)
	title = models.CharField("Course Title", max_length=50)
	description = models.TextField("Course Description", blank=True)
	old_curr = models.BooleanField("Pre-2018 Curriculum Exclusive?", default=False)
	visible = models.BooleanField("Visible?", default=True)
	prereqs = models.ManyToManyField('self', blank=True, default=None, symmetrical=False, related_name="preq")
	coreqs = models.ManyToManyField('self', blank=True, default=None,symmetrical=False , related_name="creq")
	lastupdated = models.DateTimeField("Last Updated", default=timezone.now)

	imageID = models.CharField("Photo ID", max_length=40, blank=True, null=True, default=None)

	def __str__(self):
		return	'{}'.format(self.name)

	def save(self, *args, **kwargs):
		self.number_len = len(self.number)
		return super(Course, self).save(*args, **kwargs)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['code', 'number'], name='unique codenums')
		]

class Language(models.Model):

	name = models.CharField(max_length=20, unique=True)
	imageID = models.CharField("Icon ID", max_length=40, blank=True, null=True, default=None)
	color = models.CharField(max_length=6, default="868686")

	def __str__(self):
		return	'{}'.format(self.name)

class ImportUser(AbstractUser):

	userID = models.AutoField(primary_key=True)
	username = models.CharField("Username", max_length=30, unique=True)
	first_name = models.CharField("First Name", max_length=30)
	middle_name = models.CharField("Middle Name", max_length=30, blank=True, null=True)
	last_name = models.CharField("Last Name", max_length=30)
	suffix = models.CharField("Suffix", max_length=10, blank=True, null=True)

	studentnum = models.PositiveIntegerField("Student Number", null=True)
	show_studentnum = models.BooleanField("Show Student Number", default=True)
	email = models.EmailField("E-mail", max_length=60)
	show_email = models.BooleanField("Show E-mail", default=True)
	course = models.CharField("Course/Degree Program", max_length=60)
	
	is_superuser = models.BooleanField("Is SuperUser?", default=False)
	exp = models.PositiveIntegerField("Experience Points", default=0)
	
	prof_picID = models.CharField("Prof Pic ID", max_length=40, blank=True, null=True, default=None)
	fave_lang = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Favorite Language")

	dark_mode = models.BooleanField("Dark Mode", default=False);
	notifications = models.BooleanField("Notifications", default=True);

	USERNAME_FIELD = 'username'

	def __str__(self):
		return	'{} - {}, {}'.format(self.username, self.last_name, self.first_name)


class Comment(models.Model):

	course_attr = models.ForeignKey(Course, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)
	body = models.CharField(max_length=240)
	
	imageID = models.CharField("Image ID", max_length=40, blank=True, null=True, default=None)
	date_posted = models.DateTimeField("Date Posted", default=timezone.now)

	def __str__(self):
		return	'Comment #{} - {}, {}'.format(self.id, self.course_attr, self.body[0:10])


class Likes(models.Model):

	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)

	def __str__(self):
		return	'Likes to Comment #{} - {}'.format(self.comment.id, self.user_attr)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['comment', 'user_attr'], name='unique like_combo')
		]

class Announcement(models.Model):

	title = models.CharField(max_length=30)
	body = JSONField()
	imageID = models.CharField("Image ID", max_length=40, blank=True, null=True, default=None)
	poster = models.ForeignKey(ImportUser, on_delete=models.SET_NULL, null=True)
	datepost = models.DateTimeField("Date Posted", default=timezone.now)

	def __str__(self):
		return	'{} - {}, {}'.format(self.title, self.datepost)

class Lesson(models.Model):

	name = models.CharField(max_length=50)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	rel_lesson = models.ManyToManyField('self', blank=True, default=None)
	lab_lesson = models.BooleanField("Lab Lesson?", default=False)
	extra = models.BooleanField("Extra?", default=False)
	verified = models.BooleanField("Verified?", default=False)
	verifier = models.CharField(max_length=50)

	order = models.PositiveIntegerField(default=1)

	def __str__(self):
		return	'{}: {}'.format(self.course, self.name)

class Question(models.Model):

	lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
	lang = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)

	module_content = models.TextField(null=True, blank=True, default=None)
	module_code = JSONField(null=True, default=None)
	custom_code = JSONField(null=True, default=None)
	qtype = models.CharField(max_length=10)

	def __str__(self):
		return	'{} - Question | Type: {}'.format(self.lesson.name, self.qtype)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['lesson', 'lang'], name='unique lesson-lang')
		]

class Partners():

	name = models.CharField(max_length=30, unique=True)
	imageID = models.CharField("Logo Image ID", max_length=40, blank=True, null=True, default=None)
	adImageID = models.CharField("Logo Image ID", max_length=40, blank=True, null=True, default=None)
	sponsor = models.BooleanField("Sponsor?", default=False)

	def __str__(self):
		return	'{}'.format(self.name)


class LessonStats(models.Model):
	
	lesson_attr = models.ForeignKey(Course, on_delete=models.CASCADE)
	user_attr = models.ForeignKey(ImportUser, on_delete=models.CASCADE)
	date_made = models.DateTimeField("Date", default=timezone.now)
	skips = models.PositiveSmallIntegerField(default=0)
	mistakes = models.PositiveSmallIntegerField(default=0)

	def __str__(self):
		return	'{0} on {1}| {2}'.format(self.user_attr, self.lesson_attr, self.date_made)


class BugReport(models.Model):

	name = models.CharField("Title", max_length=50)
	body = models.CharField("Body", max_length=300)
	status = models.PositiveSmallIntegerField("Status", default=0)
	lastupdated = models.DateTimeField("Last Updated", default=timezone.now)
	admin = models.ForeignKey(ImportUser, null=True, on_delete=models.SET_NULL, related_name="admin")
	user = models.ForeignKey(ImportUser, null=True, on_delete=models.SET_NULL, related_name="user")

	def __str__(self):
		return	'{} [{}]'.format(self.name, self.status)

class SiteSettings(models.Model):

	name = models.CharField(max_length=50, unique=True)
	body = models.CharField(max_length=300)

	def __str__(self):
		return	'{}'.format(self.name)

reviewer/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import ImportUser, Course


# Copy from models.py
class CourseForm(forms.Form):

	query = Course.objects.order_by('code', 'number_len', 'number')

	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'ex. CS 11', 'autocomplete': 'off'}))
	code = forms.CharField(max_length=10)
	number = forms.CharField(max_length=10)
	title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'ex. Computer Programming I', 'autocomplete': 'off'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder' : '', 'rows': 4}), required=False)
	old_curr = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False, initial=False)
	visible = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False, initial=True)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)
	lastupdated = timezone.now()
	imageID = forms.CharField(max_length=40)

	prereq = forms.ModelMultipleChoiceField(
		widget = forms.CheckboxSelectMultiple(),
        queryset = query,
        required = False
	)
	coreq = forms.ModelMultipleChoiceField(
		widget = forms.CheckboxSelectMultiple(),
        queryset = query,
        required = False
	)

class CommentForm(forms.Form):
	
	date_posted = timezone.now()

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop("request")
		user = self.request.user
		super(CommentForm, self).__init__(*args, **kwargs)

		disabled = True

		if user.is_anonymous:
			attributes = {
			'class': 'form-control -disabled', 
			'placeholder' : 'You must be logged in to comment.', 
			'readonly':'readonly'
			}
			
		else:
			attributes = { 
			'class': 'form-control comment-text-area', 
			'placeholder' : 'Comment', 
			'autocomplete': 'off'
			}
			disabled = False

		self.fields['body'] = forms.CharField(max_length=240, widget=forms.Textarea(attrs=attributes))
		self.fields['image'] = forms.ImageField(required=False, disabled=disabled)


class ImportUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm):
		model = ImportUser
		fields = ('username', 'first_name', 'middle_name', 'last_name', 'suffix', 'studentnum', 'show_studentnum', 'email', 'show_email', 'course', 'fave_lang')

class ImportUserChangeForm(UserChangeForm):

    class Meta:
        model = ImportUser
        fields = ('username', 'first_name', 'middle_name', 'last_name', 'suffix', 'studentnum', 'show_studentnum', 'email', 'show_email', 'course', 'fave_lang', 'dark_mode')

class LanguageForm(forms.Form):

	name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}))
	imageID = forms.CharField(max_length=40)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)
	color = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'class': 'color-picker', 'autocomplete': 'off'}))

class ImportImageForm(forms.Form):

	imageID = forms.CharField(max_length=40)
	imagehascleared = forms.BooleanField(widget=forms.CheckboxInput(attrs={ 'class': 'form-check-input' }), required=False,initial=False)

reviewer/views/announcements.py
import json
from ..models import Announcement
from django.shortcuts import render


def announcement_view(request, id):

	announcement = Announcement.objects.get(id=id)

	context = {
		'announcement' : announcement,
		'announcement_json' : json.dumps(announcement.body),
	}

	return render(request, 'reviewer/announcement.html', context)


def announcements(request):

	announcements = Announcement.objects.order_by('-datepost')
	
	context = {'announcements': announcements}
	return render(request, 'reviewer/announcement-list.html', context)

reviewer/views/index.py
import json
from ..models import Announcement
from django.shortcuts import render

# Index View

def index(request):
	announcements = Announcement.objects.order_by('-datepost')[0:3]
	announcements_json = []

	for announcement in announcements:
		announcements_json.append(json.dumps(announcement.body))

	context = { 
		'announcements': announcements, 
		'announcements_json' : announcements_json,
		'is_home': True
	}

	return render(request, 'reviewer/index.html', context)

reviewer/views/misc.py
from ..models import BugReport
from django.conf import settings
from django.http import JsonResponse, StreamingHttpResponse
from django.shortcuts import render
import time

from ..custom import *

# Create your views here.

def terms(request):
	context = {}
	return render(request, 'reviewer/legal/terms.html', context)

def privacy(request):
	context = {}
	return render(request, 'reviewer/legal/privacy.html', context)

def disclaimer(request):
	context = {}
	return render(request, 'reviewer/legal/disclaimer.html', context)

def bug_report_list(request):
	mybugreports = BugReport.objects.filter(user=request.user).order_by('-lastupdated')
	context = {'my_bugreports': mybugreports}
	return render(request, 'reviewer/user/user-bug_report.html', context)

def google_test(request):
	service = gdrive_connect()
	trashed = gdrive_list_meta(service, query="trashed = true", pageSize=10)
	if trashed != None:
		for i in trashed:
			gdrive_delete_file(service, i)

	retjson = {'obj': gdrive_list_meta_children(service)}

	return JsonResponse(retjson)

def stream_chunks():
	i = 0
	while i < 30:
		yield '{}\n'.format(i)
		time.sleep(1)
		i = i+1

def stream_test(request):
	return StreamingHttpResponse(stream_chunks())

reviewer/views/robots.py
from django.http import HttpResponse
from django.views.decorators.http import require_GET

@require_GET
def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /su/",
        "Disallow: /u/settings/",
        "Disallow: /u/field_check/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

reviewer/templates/reviewer/partials/coding-scripts.html
{% load static %}
{% if question.lang.name|lower == "python" %}
	<script src="{% static 'reviewer/js/skulpt.min.js' %}"></script>
    <script src="{% static 'reviewer/js/skulpt-stdlib.js' %}"></script>
    <script>
    	let pythonSk = {
    		print: function(text){
    			$(".import-code-console").append(text);
    		},
    		builtinRead: function(x) {
				if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
					throw "File not found: '" + x + "'";
				return Sk.builtinFiles["files"][x];
			},
			success: function(mod) {
				console.log('success');
			},
			error: function(err) {
				console.log(err.toString());
			},
			run: function() { 
			   let program = importApp.builder.editor.session.getValue(); 
			   var codeConsole =  $(".import-code-console"); 
			   codeConsole.empty();
			   Sk.pre = "import-code-console";
			   Sk.configure({ output: pythonSk.print , read: pythonSk.builtinRead }); 
			   //(Sk.TurtleGraphics || (Sk.TurtleGraphics = {})).target = 'mycanvas';
			   var myPromise = Sk.misceval.asyncToPromise(function() {
			       return Sk.importMainWithBody("<stdin>", false, program, true);
			   });
			   myPromise.then(pythonSk.success, pythonSk.error);
			}
    	}

    	importApp.builder.editor.session.setMode("ace/mode/python");
    	$("body").on("click", "#import-code-test", function(event){pythonSk.run();});
    </script>
{% endif %}

reviewer/templates/reviewer/partials/comment.html
{% load static %}

{% with request.resolver_match.view_name as view_name %}
<article class="py-4 px-4 d-flex {% if view_name != 'course' and view_name != 'coursecpage' and forloop.counter0 == 0  %} my-3 {% else %} mb-3 {% endif %}comment" data-comment-id="comment-{{comment.base.id}}" data-code="{{comment.base.course_attr.code|lower}}" data-number="{{comment.base.course_attr.number}}">

	{% if comment.base.user_attr != user or view_name == 'course' %}
	<a href="{% url 'user' comment.base.user_attr.username %}">{% endif %}
		<div>
			<img class="user-pic-thumb" src="{% if comment.base.user_attr.prof_picID %}
			https://drive.google.com/thumbnail?id={{comment.base.user_attr.prof_picID | urlencode }}
			{% else %}
				{% static 'reviewer/images/default_profile.png' %}
			{% endif %}
			">
		</div>
	{% if comment.base.user_attr != user  or view_name == 'course' %}
	</a>
	{% endif %}
	
	<div class="ml-4 w-100">
		<div class="w-100">
			<div class="d-flex w-100 justify-content-between">
				<span class="d-inline-flex">
					<strong class="comment-username my-auto">
						{% if comment.base.user_attr != user or view_name == 'course' %}
							<a href="{% url 'user' comment.base.user_attr.username %}" class="comment-username">
						{% endif %}
								{{comment.base.user_attr.username}}
						{% if comment.base.user_attr != user or view_name == 'course' %}
							</a>
						{% endif %}
					</strong> 
					{% if view_name != 'course' and view_name != 'coursecpage' %}
						<a class="text-muted user-comment-course-link my-auto d-flex" href="{% url 'course' comment.base.course_attr.code|lower comment.base.course_attr.number  %}" >
							<small class="d-inline-flex my-auto align-items-center">
								<i class="material-icons mx-1 material-icon-x-sm">arrow_forward</i>
								<span>{{comment.base.course_attr.name}}</span>
							</small>
						</a>
					{% endif %}
				</span>
				<div class="float-right" style="height:0">
					<div class="position-relative py-1 px-2 comment-action d-flex">
						<div class="d-inline-flex ml-auto my-auto">
							<span class="mr-3 my-auto d-flex">
								<i class="material-icons material-icon-sm{% if user.is_authenticated %} comment-like{%endif%}{% if comment.liked %} liked{%endif%}">
									star{% if not comment.liked %}_border{%endif%}
								</i> 
								<div class="my-auto ml-1 mr-2 comment-like-count inline-block">
									{{ comment.base.likes_set.all.count }}
								</div>
								{% if user == comment.base.user_attr %}
									<i class="material-icons  material-icon-sm comment-delete" title="Delete comment">delete</i>
								{% endif %}
							</span>
							<small class="my-auto">{{comment.base.date_posted|date:"M d, Y, h:i A"}}</small>
						</div>
					</div>
				</div>
			</div>
			<div class="comment-body mt-1">
				{{comment.proc|safe|linebreaks}}
			</div>
		</div>
		{% if comment.base.imageID %}
			<img class="mt-3 d-block comment-image" src="https://drive.google.com/uc?export=view&id={{comment.base.imageID | urlencode}}">
		{% else %}
		<div style="max-width: 600px;">
			{{comment.media|safe}}
		</div>
		{% endif %}
	
	</div>
</article>
			
{% endwith %}

reviewer/templates/reviewer/partials/favicon.html
{% load static %}
<link rel="icon" href="{% static 'reviewer/favicon.ico' %}" type="image/x-icon">
<link rel="shortcut icon" href="{% static 'reviewer/favicon.ico' %}" type="image/x-icon">
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'reviewer/images/favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'reviewer/images/favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'reviewer/images/favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'reviewer/images/favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'reviewer/images/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'reviewer/images/favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'reviewer/images/favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'reviewer/images/favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'reviewer/images/favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'reviewer/images/favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'reviewer/images/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'reviewer/images/favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'reviewer/images/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'reviewer/images/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'reviewer/images/favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">

reviewer/templates/reviewer/partials/footer.html
{% load static %}
<footer class=" import-footer">
	<div class="d-flex w-100 px-4 py-4">
		<div class="container">
			<div class="d-flex justify-content-between">
				<div class="my-auto">
					<small>
						<a href="{% url 'disclaimer' %}" class="import-ex-link">Disclaimer</a>
						<span class="mx-2">•</span>
						<a href="{% url 'terms' %}" class="import-ex-link">Terms & Conditions</a>
						<span class="mx-2">•</span>
						<a href="{% url 'privacy_policy' %}" class="import-ex-link">Privacy & Cookie Policy</a>
					</small>
				</div>
				<div class="d-flex ml-auto my-auto">
					<img src="{% static 'reviewer/images/esc-sm.png' %}" style="max-height: 40px" alt="Engineering Student Council" class="my-auto">
					<img src="{% static 'reviewer/images/csnet-sm.png' %}" style="max-height: 55px" alt="CS Network" class="my-auto ml-3">
				</div>
			</div>
		</div>
	</div>
</footer>

reviewer/templates/reviewer/partials/header.html
{% load static %}
<header class="d-flex navbar import-header position-fixed py-3 {% if is_home %}home-header{%endif%}">
	<div class="container d-flex justify-content-between py-2">
		<a href="{% url 'index'%}" class="import-logo">
			<div class="noselect">
				<h2 class="h2 mb-0" ><strong>import <span class="import-font-primary"><sup>*</sup></span></strong></h2>
			</div>
		</a>
		<nav class="d-flex">
			<span class="mx-3 my-auto d-none d-lg-block"><a href="{% url 'courselist' %}">Courses</a></span>
			{% if user.is_authenticated %}
				<div class="mx-3 my-auto d-none d-lg-block dropdown header-toggle" >
					<a class="d-flex my-auto dropdown-toggle"  role="button" id="HeaderProfileDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<img class="user-pic mr-2 my-auto" style="overflow:hidden" src="
						{% if user.prof_picID %}
						https://drive.google.com/thumbnail?id={{user.prof_picID | urlencode }}
						{% else %}
							{% static 'reviewer/images/default_profile.png' %}
						{% endif %}
						">
						<span class="my-auto">{{user.username}}</span>
					</a>
					<div class="dropdown-menu mt-1 dropdown-menu-right" aria-labelledby="HeaderProfileDrop">
						<a class="dropdown-item d-inline-flex justify-content-start px-4" href="{% url 'user' user.username %}">
							<i class="material-icons material-icon-sm my-auto ml-0 mr-2">
							account_circle
							</i>
							<span class="my-auto">Go to Profile</span>
						</a>
						<a class="dropdown-item d-inline-flex justify-content-start px-4" href="{% url 'user_settings' %}">
							<i class="material-icons material-icon-sm my-auto ml-0 mr-2">
							settings
							</i>
							<span class="my-auto">Profile Settings</span>
						</a>
						<a class="dropdown-item d-inline-flex justify-content-start px-4" href="#">
							<i class="material-icons material-icon-sm my-auto ml-0 mr-2">
							bug_report
							</i>
							<span class="my-auto">Report a Bug</span>
						</a>
						{% if user.is_superuser %}
							<div class="dropdown-divider"></div>
							<a class="dropdown-item d-inline-flex justify-content-start px-4" href="{% url 'admin' %}">
								<i class="material-icons material-icon-sm my-auto ml-0 mr-2">
								assessment
								</i>
								<span class="my-auto">Admin Dashboard</span>
							</a> 
						{% endif %}
						<div class="dropdown-divider"></div>
						<a class="dropdown-item d-inline-flex justify-content-start px-4" href="{% url 'logout' %}">
							<i class="material-icons material-icon-sm my-auto ml-0 mr-2">
							exit_to_app
							</i>
							<span class="my-auto">Logout</span>
						</a>
					</div>
				</div>

			{% else %}
				<span class="mx-3 my-auto d-none d-lg-block"><a href="{% url 'login' %}">Login</a></span>
			{% endif %}
			<i class="material-icons mx-3 mr-lg-0 my-auto">search</i>
			<i class="material-icons my-auto d-block d-lg-none">menu</i>
		</nav>
	</div>
</header>